spring:
  application:
    name: multiple-database-app

  db1:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/multiple-database-app
    username: root
    password: root123
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      format-sql: true

  db2:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/multiple-database-app
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 1






